const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "0626753818";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false""  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "SUHAIL_10_40_07_27_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDgsXG4gICAgICAgIDY4LFxuICAgICAgICA3MCxcbiAgICAgICAgNTgsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjE2LFxuICAgICAgICAxNSxcbiAgICAgICAgMTg4LFxuICAgICAgICAxOSxcbiAgICAgICAgMTA2LFxuICAgICAgICAxOSxcbiAgICAgICAgMjIxLFxuICAgICAgICAyMDYsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTU4LFxuICAgICAgICAxMTAsXG4gICAgICAgIDE0MixcbiAgICAgICAgOTgsXG4gICAgICAgIDE4MCxcbiAgICAgICAgNjMsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTQ3LFxuICAgICAgICA0OSxcbiAgICAgICAgMTMzLFxuICAgICAgICA4MSxcbiAgICAgICAgNDcsXG4gICAgICAgIDc5LFxuICAgICAgICAxMzcsXG4gICAgICAgIDcsXG4gICAgICAgIDIwMyxcbiAgICAgICAgNzcsXG4gICAgICAgIDEyMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxOTQsXG4gICAgICAgIDM4LFxuICAgICAgICA0NCxcbiAgICAgICAgMzEsXG4gICAgICAgIDE4OSxcbiAgICAgICAgOTEsXG4gICAgICAgIDM1LFxuICAgICAgICA1OCxcbiAgICAgICAgNzksXG4gICAgICAgIDExNCxcbiAgICAgICAgMjU0LFxuICAgICAgICA5MixcbiAgICAgICAgNDUsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMjQzLFxuICAgICAgICAyMTEsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTgyLFxuICAgICAgICAyMjUsXG4gICAgICAgIDYxLFxuICAgICAgICAyMDksXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjI4LFxuICAgICAgICA0MSxcbiAgICAgICAgMTMwLFxuICAgICAgICAyMyxcbiAgICAgICAgMTgsXG4gICAgICAgIDEzOSxcbiAgICAgICAgOCxcbiAgICAgICAgMTAxLFxuICAgICAgICAxNTksXG4gICAgICAgIDM1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxODQsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjAsXG4gICAgICAgIDE0LFxuICAgICAgICAxOTEsXG4gICAgICAgIDkwLFxuICAgICAgICAyNDAsXG4gICAgICAgIDI5LFxuICAgICAgICAxNSxcbiAgICAgICAgMTczLFxuICAgICAgICAyNixcbiAgICAgICAgMjE1LFxuICAgICAgICAxODgsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjgsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTI3LFxuICAgICAgICAxNzAsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjUsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTI3LFxuICAgICAgICA1OCxcbiAgICAgICAgNTcsXG4gICAgICAgIDEyLFxuICAgICAgICAxNjAsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTgsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjQ5LFxuICAgICAgICAyMTksXG4gICAgICAgIDExNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNDQsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTU2LFxuICAgICAgICAzMyxcbiAgICAgICAgMjUyLFxuICAgICAgICAxMTIsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTM2LFxuICAgICAgICAyNDksXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTM1LFxuICAgICAgICAyNDMsXG4gICAgICAgIDIzMyxcbiAgICAgICAgODksXG4gICAgICAgIDc2LFxuICAgICAgICA5OSxcbiAgICAgICAgMTc5LFxuICAgICAgICA5LFxuICAgICAgICA0LFxuICAgICAgICAyNDIsXG4gICAgICAgIDIwLFxuICAgICAgICAxNjQsXG4gICAgICAgIDExOCxcbiAgICAgICAgNzMsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjAsXG4gICAgICAgIDIsXG4gICAgICAgIDE3LFxuICAgICAgICAyMixcbiAgICAgICAgMTU0LFxuICAgICAgICAyNDksXG4gICAgICAgIDk5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0OCxcbiAgICAgICAgMjI0LFxuICAgICAgICAxMjYsXG4gICAgICAgIDgwLFxuICAgICAgICAxNSxcbiAgICAgICAgNjYsXG4gICAgICAgIDYsXG4gICAgICAgIDI3LFxuICAgICAgICA2OCxcbiAgICAgICAgMjI4LFxuICAgICAgICA0OCxcbiAgICAgICAgMTc3LFxuICAgICAgICA4NSxcbiAgICAgICAgMzUsXG4gICAgICAgIDY5LFxuICAgICAgICA2NSxcbiAgICAgICAgMTQ4LFxuICAgICAgICA1MyxcbiAgICAgICAgMjAyLFxuICAgICAgICAzMixcbiAgICAgICAgMTQ5LFxuICAgICAgICAzMixcbiAgICAgICAgMjE5LFxuICAgICAgICA0NyxcbiAgICAgICAgMjI5LFxuICAgICAgICAxMTcsXG4gICAgICAgIDIzLFxuICAgICAgICAxNjYsXG4gICAgICAgIDEyNyxcbiAgICAgICAgODcsXG4gICAgICAgIDIwNixcbiAgICAgICAgODVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI2LFxuICAgICAgICAxODIsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTcwLFxuICAgICAgICAyMDEsXG4gICAgICAgIDk5LFxuICAgICAgICA2NixcbiAgICAgICAgMTIxLFxuICAgICAgICAxNDUsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTY1LFxuICAgICAgICAxOTIsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTYwLFxuICAgICAgICAxODAsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTYzLFxuICAgICAgICAxNjEsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTE4LFxuICAgICAgICAxODcsXG4gICAgICAgIDExNCxcbiAgICAgICAgMzQsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjA2LFxuICAgICAgICAxNDcsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTUyLFxuICAgICAgICAyMzgsXG4gICAgICAgIDc2LFxuICAgICAgICAyNSxcbiAgICAgICAgMTE1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDgwLFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAxNTYsXG4gICAgICAgICAgNTIsXG4gICAgICAgICAgNDcsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDEwOVxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICA4MSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDE4NSxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDIxMCxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICA2NCxcbiAgICAgICAgICAxNixcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgNDZcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDMsXG4gICAgICAgIDMsXG4gICAgICAgIDI1MCxcbiAgICAgICAgNjMsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjIzLFxuICAgICAgICAxOTYsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTI0LFxuICAgICAgICA3MixcbiAgICAgICAgNjAsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTEyLFxuICAgICAgICAxNDgsXG4gICAgICAgIDYsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTAxLFxuICAgICAgICAxMDksXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTEyLFxuICAgICAgICAyMTYsXG4gICAgICAgIDk1LFxuICAgICAgICAxNzksXG4gICAgICAgIDE5NixcbiAgICAgICAgMTc5LFxuICAgICAgICA2MyxcbiAgICAgICAgMjI4LFxuICAgICAgICAxNjEsXG4gICAgICAgIDExLFxuICAgICAgICAxMSxcbiAgICAgICAgMjMxLFxuICAgICAgICAxNDksXG4gICAgICAgIDExNCxcbiAgICAgICAgODEsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNTgsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTksXG4gICAgICAgIDE4NixcbiAgICAgICAgMTQwLFxuICAgICAgICAxNzUsXG4gICAgICAgIDEwLFxuICAgICAgICAxMDgsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTQsXG4gICAgICAgIDE5NCxcbiAgICAgICAgOTcsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjQyLFxuICAgICAgICAyNDAsXG4gICAgICAgIDE5MSxcbiAgICAgICAgNDMsXG4gICAgICAgIDI0MixcbiAgICAgICAgNjcsXG4gICAgICAgIDc3LFxuICAgICAgICAyMDgsXG4gICAgICAgIDUyLFxuICAgICAgICA0OCxcbiAgICAgICAgMTM5LFxuICAgICAgICAyNDIsXG4gICAgICAgIDkyLFxuICAgICAgICAzMyxcbiAgICAgICAgNzcsXG4gICAgICAgIDEzN1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTEwLFxuICBcImFkdlNlY3JldEtleVwiOiBcIlAvNEdEY2VpY1EwN215MGNwajVJdjE4S0R6OERxRHlISS9aZUNBdmNvNTg9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU1NzEzMTMxNTM3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJGRTNEQjQxREMyNDEyRjVGREJCNThEQ0Y1QTA1MEI1OFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjIwNzY4NTRcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyNTU3MTMxMzE1MzdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkJGNEMyQjBCMTFDMDFBNUZGOTEwNUJBODRDRUU2QUJDXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMjA3Njg1NVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJkQlRRX3BQLVJEV3NSVkdNdUI3Q25RXCIsXG4gIFwicGhvbmVJZFwiOiBcIjI0ZWYyNzE5LWY4ZDMtNDdiMi05NTcwLTRlZjg1MzJhMTQ0ZlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxNTAsXG4gICAgICAyMzQsXG4gICAgICA4MSxcbiAgICAgIDIxMyxcbiAgICAgIDE2NCxcbiAgICAgIDE1NyxcbiAgICAgIDU5LFxuICAgICAgMzEsXG4gICAgICAyMTgsXG4gICAgICA2MSxcbiAgICAgIDE3NixcbiAgICAgIDE3NyxcbiAgICAgIDY5LFxuICAgICAgMTEzLFxuICAgICAgMTQyLFxuICAgICAgMTkyLFxuICAgICAgMjAxLFxuICAgICAgMTYzLFxuICAgICAgMzYsXG4gICAgICAxNDJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjI1LFxuICAgICAgOTgsXG4gICAgICAyMDEsXG4gICAgICAxMzMsXG4gICAgICAxNjUsXG4gICAgICAxMTMsXG4gICAgICAxODQsXG4gICAgICAyMTQsXG4gICAgICAxMjEsXG4gICAgICAxNzQsXG4gICAgICA5MSxcbiAgICAgIDE4NixcbiAgICAgIDUwLFxuICAgICAgMTMzLFxuICAgICAgMTY2LFxuICAgICAgMjEzLFxuICAgICAgMjE2LFxuICAgICAgMTQ0LFxuICAgICAgMTY3LFxuICAgICAgMjRcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiTFoyTU1MTUxcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjI1NTcxMzEzMTUzNzo1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCI0MjczODQ0ODIyMjIzOjVAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiSi5zcXVhcmVcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNPTEh2NU1DRUs2ZGs3VUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjk5ZUxBUlY4YkhXUjlFWExZdSt3aEo2S2JNckdEM0pIQ1E0TnlKeFFMM3M9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiSGxtTGk5OSs3RUppNTg1VkdKc2FXM0l2WFZZQmI2MFIwUU5QTmRRRS8zY2dZSTFzQzFKNTlNNzJtUmZ5K0pyVXZicmVwTkVDcFBtc0xSQkhJaFduQmc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwidXBWaTZmdnVhVkR3d0pmS3p5TkdJUEVtclJsamJxMkRFOXFQMjFjYmhmcXRlSU16eDRiQ1RaWVZIYU1LUElpdkp0VjYwSGtQSkdwOXJRUkt6WFBPaGc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjU1NzEzMTMxNTM3OjVAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDEzOSxcbiAgICAgICAgICAxLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgNjksXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDksXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICA4MCxcbiAgICAgICAgICA0NyxcbiAgICAgICAgICAxMjNcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyMjA3Njg0OSxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUZPclwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRk9yLmpzb24iOiAie1wia2V5RGF0YVwiOlwidnNMclg3aU1penIyeHNQc1A2RXlOUXFYUWJwYUhNS2hwaGt6NTY0QVNpWT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo1Nzc3NTgxNzgsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyMjA3Njg1MTUyNFwifSIKfQ==" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "Wakaka-Bot",
  ownername:process.env.OWNER_NAME|| "Wakaka-Bot",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
